spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: estate-agency-assistant
  data:
    mongodb:
      uri: mongodb://localhost:27017/estate-assistant-db
  ai:
    openai:
      api-key: ${SECRET_API_KEY}
      chat:
        options:
          model: gpt-5-nano
#          temperature: 1
  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .ftl
    cache: false
logging:
  level:
    org.springframework.ai.chat.client.advisor: INFO

app:
  chatbot:
    model: gpt-5-mini
  properties-generator:
    model: gpt-5-nano
  estate-agency:
    name: "Dream Homes Realty"
    location: "Hogwarts Castle, Highlands, Scotland"
    contact:
      email: "damboldor.estate@hogwarts.miracle"
      phone: "+44 1234 567890"